"""Integration test for multi-agent orchestration.

Tests verify that Workout and Meal agents execute in parallel as per FR-064
and that the AI orchestration service correctly coordinates multiple agents.

Success Criteria SC-027: AI agents execute in parallel (workout + meal generation)
FR-064: Fitness Plan Agent coordinates Workout Plan Agent and Meal Plan Agent in parallel
"""
import time

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from src.ai.agent import PlanContext, UserContext
from src.models.user import User
from src.services.ai_service import AIOrchestrationService


class TestMultiAgentOrchestration:
    """Integration tests for parallel multi-agent execution"""

    @pytest.mark.asyncio
    async def test_parallel_agent_execution(
        self,
        async_session: AsyncSession,
        test_user: User
    ):
        """Test that Workout and Meal agents execute in parallel (FR-064, SC-027)."""
        # Setup
        orchestration_service = AIOrchestrationService(async_session)

        user_context = UserContext(
            user_id=str(test_user.id),
            fitness_level="intermediate",
            dietary_restrictions=["vegetarian"],
            equipment_access=["gym", "dumbbells", "barbell"],
            preferences={
                "workout_frequency": 4,
                "meal_preferences": "high_protein"
            }
        )

        plan_context = PlanContext(
            goal_description="Build muscle and strength",
            goal_type="muscle_gain",
            duration_weeks=12,
            workout_frequency=4,
            dietary_approach="calorie_surplus",
            specific_requirements={
                "focus_areas": ["upper_body", "legs"],
                "avoid_exercises": []
            }
        )

        # Execute orchestration with timing
        start_time = time.time()

        result = await orchestration_service.generate_plan(
            user_context=user_context,
            plan_context=plan_context
        )

        end_time = time.time()
        execution_time = end_time - start_time

        # Assertions

        # 1. Verify plan was generated
        assert result is not None
        assert "fitness_plan" in result
        assert "workout_plan" in result
        assert "meal_plan" in result

        # 2. Verify workout plan was generated by Workout Agent
        workout_plan = result["workout_plan"]
        assert workout_plan is not None
        assert "workouts" in workout_plan or "exercises" in workout_plan
        assert len(workout_plan.get("workouts", workout_plan.get("exercises", []))) > 0

        # 3. Verify meal plan was generated by Meal Agent
        meal_plan = result["meal_plan"]
        assert meal_plan is not None
        assert "meals" in meal_plan or "daily_meals" in meal_plan
        assert len(meal_plan.get("meals", meal_plan.get("daily_meals", []))) > 0

        # 4. Verify parallel execution performance
        # Parallel execution should be faster than sequential
        # If agents run in parallel, total time should be close to max(agent1_time, agent2_time)
        # rather than sum(agent1_time + agent2_time)
        # For this test, we verify execution completes within reasonable time
        assert execution_time < 30, f"Parallel execution took {execution_time}s, expected < 30s"

        # 5. Verify both results are incorporated in final plan
        fitness_plan = result["fitness_plan"]
        assert fitness_plan.get("workout_plan_id") is not None
        assert fitness_plan.get("meal_plan_id") is not None

        print(f"✓ Multi-agent parallel execution completed in {execution_time:.2f}s")

    @pytest.mark.asyncio
    async def test_agent_coordination_with_dependencies(
        self,
        async_session: AsyncSession,
        test_user: User
    ):
        """Test that agents correctly use shared context and coordinate results."""
        orchestration_service = AIOrchestrationService(async_session)

        user_context = UserContext(
            user_id=str(test_user.id),
            fitness_level="beginner",
            dietary_restrictions=["gluten_free", "dairy_free"],
            equipment_access=["bodyweight"],
            preferences={
                "workout_frequency": 3,
                "meal_preferences": "simple_recipes"
            }
        )

        plan_context = PlanContext(
            goal_description="Lose weight and improve endurance",
            goal_type="weight_loss",
            duration_weeks=8,
            workout_frequency=3,
            dietary_approach="calorie_deficit",
            specific_requirements={
                "intensity_preference": "moderate",
                "avoid_exercises": ["high_impact"]
            }
        )

        result = await orchestration_service.generate_plan(
            user_context=user_context,
            plan_context=plan_context
        )

        # Verify agents respected shared context
        workout_plan = result["workout_plan"]
        meal_plan = result["meal_plan"]

        # 1. Workout plan should respect equipment constraint
        # Since user only has bodyweight, workouts should be bodyweight exercises
        assert workout_plan is not None

        # 2. Meal plan should respect dietary restrictions
        # Should not contain gluten or dairy
        assert meal_plan is not None

        # 3. Both plans should align with the same goal_type
        assert result["fitness_plan"]["goal_type"] == "weight_loss"

    @pytest.mark.asyncio
    async def test_agent_error_handling(
        self,
        async_session: AsyncSession,
        test_user: User
    ):
        """Test that orchestration handles agent failures gracefully."""
        orchestration_service = AIOrchestrationService(async_session)

        # Create context that might cause issues (empty preferences)
        user_context = UserContext(
            user_id=str(test_user.id),
            fitness_level=None,  # Missing required field
            dietary_restrictions=[],
            equipment_access=[],
            preferences={}
        )

        plan_context = PlanContext(
            goal_description="",  # Empty goal
            goal_type="muscle_gain",
            duration_weeks=0,  # Invalid duration
            workout_frequency=0,
            dietary_approach="",
            specific_requirements={}
        )

        # Should either raise exception or return error indicator
        try:
            result = await orchestration_service.generate_plan(
                user_context=user_context,
                plan_context=plan_context
            )

            # If it doesn't raise, should have error indicator
            if result is not None:
                # Check if result indicates error
                assert "error" in result or result == {}
        except (ValueError, TypeError, KeyError) as e:
            # Expected error - orchestration should validate inputs
            assert str(e) is not None
            print(f"✓ Orchestration correctly rejected invalid input: {e}")

    @pytest.mark.asyncio
    async def test_agent_result_consistency(
        self,
        async_session: AsyncSession,
        test_user: User
    ):
        """Test that multiple runs with same input produce consistent results."""
        orchestration_service = AIOrchestrationService(async_session)

        user_context = UserContext(
            user_id=str(test_user.id),
            fitness_level="intermediate",
            dietary_restrictions=[],
            equipment_access=["gym"],
            preferences={"workout_frequency": 4}
        )

        plan_context = PlanContext(
            goal_description="General fitness improvement",
            goal_type="general_fitness",
            duration_weeks=12,
            workout_frequency=4,
            dietary_approach="maintenance",
            specific_requirements={}
        )

        # Run orchestration twice
        result1 = await orchestration_service.generate_plan(
            user_context=user_context,
            plan_context=plan_context
        )

        result2 = await orchestration_service.generate_plan(
            user_context=user_context,
            plan_context=plan_context
        )

        # Both should succeed
        assert result1 is not None
        assert result2 is not None

        # Both should have similar structure (though content may vary due to AI)
        assert set(result1.keys()) == set(result2.keys())
        assert result1["fitness_plan"]["goal_type"] == result2["fitness_plan"]["goal_type"]

