"""Integration test for multi-agent orchestration.

Tests verify that Workout and Meal agents execute in parallel as per FR-064
and that the AI orchestration service correctly coordinates multiple agents.

Success Criteria SC-027: AI agents execute in parallel (workout + meal generation)
FR-064: Fitness Plan Agent coordinates Workout Plan Agent and Meal Plan Agent in parallel

NOTE: These tests are deprecated and need refactoring. The old generate_plan() method
has been removed in favor of tool-based approach where conversation_agent calls
build_fitness_plan tool directly. Tests should be updated to test the new flow.
"""
import time

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from src.models.user import User
from src.services.ai_service import AIOrchestrationService


class TestMultiAgentOrchestration:
    """Integration tests for parallel multi-agent execution"""

    @pytest.mark.skip(reason="Transaction management issues with test fixtures - needs refactoring")
    @pytest.mark.asyncio
    async def test_parallel_agent_execution(
        self,
        db_session: AsyncSession,
        test_user: User
    ):
        """Test that multiple agents can execute in parallel (FR-064, SC-027)."""
        # Setup
        orchestration_service = AIOrchestrationService(db_session)

        # Build requirements dict
        requirements = {
            "goal": "Build muscle and strength",
            "goal_type": "muscle_gain",
            "duration_weeks": 12,
            "workout_frequency": 4,
            "dietary_approach": "calorie_surplus",
            "focus_areas": ["upper_body", "legs"],
            "avoid_exercises": [],
            "fitness_level": "intermediate",
            "dietary_restrictions": ["vegetarian"],
            "equipment_access": ["gym", "dumbbells", "barbell"]
        }

        # Create a conversation for testing
        from src.services.conversation_service import ConversationService
        conv_service = ConversationService(db_session)
        conversation = await conv_service.create_conversation(
            user_id=test_user.id,
            conversation_type="plan_creation"
        )

        # Execute orchestration with timing
        start_time = time.time()

        result = await orchestration_service.generate_plan(
            user=test_user,
            conversation_id=str(conversation.id),
            requirements=requirements
        )

        end_time = time.time()
        execution_time = end_time - start_time

        # Assertions

        # 1. Verify plan was generated
        assert result is not None
        assert "fitness_plan" in result
        assert "workout_plan" in result
        assert "meal_plan" in result

        # 2. Verify workout plan was generated by Workout Agent
        workout_plan = result["workout_plan"]
        assert workout_plan is not None
        assert "workouts" in workout_plan or "exercises" in workout_plan
        assert len(workout_plan.get("workouts", workout_plan.get("exercises", []))) > 0

        # 3. Verify meal plan was generated by Meal Agent
        meal_plan = result["meal_plan"]
        assert meal_plan is not None
        assert "meals" in meal_plan or "daily_meals" in meal_plan
        assert len(meal_plan.get("meals", meal_plan.get("daily_meals", []))) > 0

        # 4. Verify parallel execution performance
        # Parallel execution should be faster than sequential
        # If agents run in parallel, total time should be close to max(agent1_time, agent2_time)
        # rather than sum(agent1_time + agent2_time)
        # For this test, we verify execution completes within reasonable time
        assert execution_time < 30, f"Parallel execution took {execution_time}s, expected < 30s"

        # 5. Verify both results are incorporated in final plan
        fitness_plan = result["fitness_plan"]
        assert fitness_plan.get("workout_plan_id") is not None
        assert fitness_plan.get("meal_plan_id") is not None

        print(f"✓ Multi-agent parallel execution completed in {execution_time:.2f}s")

    @pytest.mark.skip(reason="Transaction management issues with test fixtures - needs refactoring")
    @pytest.mark.asyncio
    async def test_agent_coordination_with_dependencies(
        self,
        db_session: AsyncSession,
        test_user: User
    ):
        """Test that agents correctly use shared context and coordinate results."""
        orchestration_service = AIOrchestrationService(db_session)

        # Create a conversation for testing
        from src.services.conversation_service import ConversationService
        conv_service = ConversationService(db_session)
        conversation = await conv_service.create_conversation(
            user_id=test_user.id,
            conversation_type="plan_creation"
        )

        requirements = {
            "goal": "Lose weight and improve endurance",
            "goal_type": "weight_loss",
            "duration_weeks": 8,
            "workout_frequency": 3,
            "dietary_approach": "calorie_deficit",
            "fitness_level": "beginner",
            "dietary_restrictions": ["gluten_free", "dairy_free"],
            "equipment_access": ["bodyweight"],
            "intensity_preference": "moderate",
            "avoid_exercises": ["high_impact"]
        }

        from src.services.conversation_service import ConversationService
        conv_service = ConversationService(db_session)
        conversation = await conv_service.create_conversation(
            user_id=test_user.id,
            conversation_type="plan_creation"
        )
        await db_session.commit()

        result = await orchestration_service.generate_plan(
            user=test_user,
            conversation_id=str(conversation.id),
            requirements=requirements
        )

        # Verify agents respected shared context
        workout_plan = result["workout_plan"]
        meal_plan = result["meal_plan"]

        # 1. Workout plan should respect equipment constraint
        # Since user only has bodyweight, workouts should be bodyweight exercises
        assert workout_plan is not None

        # 2. Meal plan should respect dietary restrictions
        # Should not contain gluten or dairy
        assert meal_plan is not None

        # 3. Both plans should align with the same goal_type
        assert result["fitness_plan"]["goal_type"] == "weight_loss"

    @pytest.mark.skip(reason="Transaction management issues with test fixtures - needs refactoring")
    @pytest.mark.asyncio
    async def test_agent_error_handling(
        self,
        db_session: AsyncSession,
        test_user: User
    ):
        """Test that orchestration handles agent failures gracefully."""
        orchestration_service = AIOrchestrationService(db_session)

        # Create requirements that might cause issues
        requirements = {
            "goal": "",  # Empty goal
            "goal_type": "muscle_gain",
            "duration_weeks": 0,  # Invalid duration
            "workout_frequency": 0,
            "dietary_approach": "",
            "fitness_level": None,
            "dietary_restrictions": [],
            "equipment_access": []
        }

        from src.services.conversation_service import ConversationService
        conv_service = ConversationService(db_session)
        conversation = await conv_service.create_conversation(
            user_id=test_user.id,
            conversation_type="plan_creation"
        )
        await db_session.commit()

        # Should either raise exception or return error indicator
        try:
            result = await orchestration_service.generate_plan(
                user=test_user,
                conversation_id=str(conversation.id),
                requirements=requirements
            )

            # If it doesn't raise, should have error indicator
            if result is not None:
                # Check if result indicates error
                assert "error" in result or result == {}
        except (ValueError, TypeError, KeyError) as e:
            # Expected error - orchestration should validate inputs
            assert str(e) is not None
            print(f"✓ Orchestration correctly rejected invalid input: {e}")

    @pytest.mark.skip(reason="Transaction management issues with test fixtures - needs refactoring")
    @pytest.mark.asyncio
    async def test_agent_result_consistency(
        self,
        db_session: AsyncSession,
        test_user: User
    ):
        """Test that multiple runs with same input produce consistent results."""
        orchestration_service = AIOrchestrationService(db_session)

        # Create conversations for testing
        from src.services.conversation_service import ConversationService
        conv_service = ConversationService(db_session)
        conversation1 = await conv_service.create_conversation(
            user_id=test_user.id,
            conversation_type="plan_creation"
        )
        conversation2 = await conv_service.create_conversation(
            user_id=test_user.id,
            conversation_type="plan_creation"
        )

        requirements = {
            "goal": "General fitness improvement",
            "goal_type": "general_fitness",
            "duration_weeks": 12,
            "workout_frequency": 4,
            "dietary_approach": "maintenance",
            "fitness_level": "intermediate",
            "dietary_restrictions": [],
            "equipment_access": ["gym"]
        }

        # Run orchestration twice
        result1 = await orchestration_service.generate_plan(
            user=test_user,
            conversation_id=str(conversation1.id),
            requirements=requirements
        )

        result2 = await orchestration_service.generate_plan(
            user=test_user,
            conversation_id=str(conversation2.id),
            requirements=requirements
        )

        # Both should succeed
        assert result1 is not None
        assert result2 is not None

        # Both should have similar structure (though content may vary due to AI)
        assert set(result1.keys()) == set(result2.keys())
        assert result1["fitness_plan"]["goal_type"] == result2["fitness_plan"]["goal_type"]

