"""add_title_to_conversations

Revision ID: 21a1135198bf
Revises: 14c0d288270b
Create Date: 2025-12-12 11:55:29.464750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a1135198bf'
down_revision: Union[str, None] = '14c0d288270b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exercise_catalog_embedding', table_name='exercise_catalog', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ix_exercise_catalog_difficulty', table_name='exercise_catalog')
    op.drop_index('ix_exercise_catalog_exercise_type', table_name='exercise_catalog')
    op.drop_index('ix_exercise_catalog_name', table_name='exercise_catalog')
    op.drop_table('exercise_catalog')
    op.add_column('conversations', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.alter_column('disruption_events', 'resolution_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_disruption_events_conversation', table_name='disruption_events')
    op.drop_index('idx_disruption_events_fitness_plan', table_name='disruption_events')
    op.drop_index('idx_disruption_events_start_date', table_name='disruption_events')
    op.drop_index('idx_disruption_events_status', table_name='disruption_events')
    op.drop_index('idx_disruption_events_user', table_name='disruption_events')
    op.drop_index('idx_disruption_events_user_plan', table_name='disruption_events')
    op.drop_index('ix_disruption_events_start_date', table_name='disruption_events')
    op.create_index(op.f('ix_disruption_events_conversation_id'), 'disruption_events', ['conversation_id'], unique=False)
    op.create_unique_constraint(None, 'disruption_events', ['id'])
    op.drop_index('idx_exercises_embedding', table_name='exercises', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ix_fitness_plans_status', table_name='fitness_plans')
    op.drop_index('ix_fitness_plans_user_status', table_name='fitness_plans')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_progress_records_fitness_plan_id', table_name='progress_records')
    op.drop_index('ix_progress_records_record_date', table_name='progress_records')
    op.drop_index('ix_progress_records_record_type', table_name='progress_records')
    op.drop_index('ix_progress_records_user_id', table_name='progress_records')
    op.drop_index('ix_schedule_entries_completion_status', table_name='schedule_entries')
    op.drop_index('ix_schedule_entries_entry_date', table_name='schedule_entries')
    op.drop_index('ix_schedule_entries_schedule_id', table_name='schedule_entries')
    op.drop_index('ix_schedule_entries_user_date', table_name='schedule_entries')
    op.alter_column('schedules', 'last_recalculated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'last_recalculated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_schedule_entries_user_date', 'schedule_entries', ['schedule_id', 'entry_date'], unique=False)
    op.create_index('ix_schedule_entries_schedule_id', 'schedule_entries', ['schedule_id'], unique=False)
    op.create_index('ix_schedule_entries_entry_date', 'schedule_entries', ['entry_date'], unique=False)
    op.create_index('ix_schedule_entries_completion_status', 'schedule_entries', ['completion_status'], unique=False)
    op.create_index('ix_progress_records_user_id', 'progress_records', ['user_id'], unique=False)
    op.create_index('ix_progress_records_record_type', 'progress_records', ['record_type'], unique=False)
    op.create_index('ix_progress_records_record_date', 'progress_records', ['record_date'], unique=False)
    op.create_index('ix_progress_records_fitness_plan_id', 'progress_records', ['fitness_plan_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_fitness_plans_user_status', 'fitness_plans', ['user_id', 'status'], unique=False)
    op.create_index('ix_fitness_plans_status', 'fitness_plans', ['status'], unique=False)
    op.create_index('idx_exercises_embedding', 'exercises', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(None, 'disruption_events', type_='unique')
    op.drop_index(op.f('ix_disruption_events_conversation_id'), table_name='disruption_events')
    op.create_index('ix_disruption_events_start_date', 'disruption_events', ['start_date'], unique=False)
    op.create_index('idx_disruption_events_user_plan', 'disruption_events', ['user_id', 'fitness_plan_id'], unique=False)
    op.create_index('idx_disruption_events_user', 'disruption_events', ['user_id'], unique=False)
    op.create_index('idx_disruption_events_status', 'disruption_events', ['status'], unique=False)
    op.create_index('idx_disruption_events_start_date', 'disruption_events', ['start_date'], unique=False)
    op.create_index('idx_disruption_events_fitness_plan', 'disruption_events', ['fitness_plan_id'], unique=False)
    op.create_index('idx_disruption_events_conversation', 'disruption_events', ['conversation_id'], unique=False)
    op.alter_column('disruption_events', 'resolution_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_conversations_status', 'conversations', ['status'], unique=False)
    op.drop_column('conversations', 'title')
    op.create_table('exercise_catalog',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_muscle_groups', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('equipment_required', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('form_cues', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('alternatives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='exercise_catalog_id_key')
    )
    op.create_index('ix_exercise_catalog_name', 'exercise_catalog', ['name'], unique=False)
    op.create_index('ix_exercise_catalog_exercise_type', 'exercise_catalog', ['exercise_type'], unique=False)
    op.create_index('ix_exercise_catalog_difficulty', 'exercise_catalog', ['difficulty'], unique=False)
    op.create_index('idx_exercise_catalog_embedding', 'exercise_catalog', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
