"""user_story_1_plan_creation

Revision ID: 370efd33ab6c
Revises: 
Create Date: 2025-11-15 11:17:31.398649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370efd33ab6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('height_cm', sa.String(length=10), nullable=True),
    sa.Column('weight_kg', sa.String(length=10), nullable=True),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('equipment_access', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fitness_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=False),
    sa.Column('target_weight_kg', sa.String(length=10), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'abandoned', name='plan_status'), nullable=False),
    sa.Column('plan_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_fitness_plans_user_id'), 'fitness_plans', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fitness_plan_id', sa.UUID(), nullable=True),
    sa.Column('conversation_type', sa.Enum('plan_creation', 'plan_update', 'general_question', name='conversation_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='conversation_status'), nullable=False),
    sa.Column('conversation_context', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_conversations_fitness_plan_id'), 'conversations', ['fitness_plan_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('fitness_plan_id', sa.UUID(), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=False),
    sa.Column('macronutrient_distribution', sa.JSON(), nullable=False),
    sa.Column('protein_grams_target', sa.Integer(), nullable=False),
    sa.Column('carbs_grams_target', sa.Integer(), nullable=False),
    sa.Column('fats_grams_target', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_fitness_plan_id'), 'meal_plans', ['fitness_plan_id'], unique=False)
    op.create_table('phases',
    sa.Column('fitness_plan_id', sa.UUID(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phase_details', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_phases_fitness_plan_id'), 'phases', ['fitness_plan_id'], unique=False)
    op.create_table('workout_plans',
    sa.Column('fitness_plan_id', sa.UUID(), nullable=False),
    sa.Column('frequency_per_week', sa.Integer(), nullable=False),
    sa.Column('progression_strategy', sa.String(length=255), nullable=False),
    sa.Column('workout_plan_details', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_fitness_plan_id'), 'workout_plans', ['fitness_plan_id'], unique=False)
    op.create_table('meals',
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('meal_type', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbs_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fats_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('meal_details', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_meals_meal_plan_id'), 'meals', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_meals_phase_id'), 'meals', ['phase_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('user', 'assistant', 'system', name='sender_type'), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('function_calls', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('workouts',
    sa.Column('workout_plan_id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workout_type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity_level', sa.String(length=50), nullable=False),
    sa.Column('workout_structure', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_workouts_phase_id'), 'workouts', ['phase_id'], unique=False)
    op.create_index(op.f('ix_workouts_workout_plan_id'), 'workouts', ['workout_plan_id'], unique=False)
    op.create_table('exercises',
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.String(length=100), nullable=False),
    sa.Column('target_muscle_groups', sa.JSON(), nullable=False),
    sa.Column('equipment_required', sa.JSON(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.String(length=50), nullable=True),
    sa.Column('rpe_target', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('form_cues', sa.JSON(), nullable=True),
    sa.Column('alternative_exercise_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_exercises_workout_id'), 'exercises', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_workout_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_workouts_workout_plan_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_phase_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_meals_phase_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_plan_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_workout_plans_fitness_plan_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_phases_fitness_plan_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_meal_plans_fitness_plan_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_fitness_plan_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_fitness_plans_user_id'), table_name='fitness_plans')
    op.drop_table('fitness_plans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
