"""add_plan_message_type

Revision ID: 053b0b9e9e70
Revises: a28154bf3f90
Create Date: 2025-12-12 21:07:25.154462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053b0b9e9e70'
down_revision: Union[str, None] = 'a28154bf3f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'plan' to sender_type enum
    op.execute("ALTER TYPE sender_type ADD VALUE 'plan'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'fitness_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'plan_id')
    # ### end Alembic commands ###
    
    # Note: PostgreSQL doesn't support removing enum values directly
    # You would need to recreate the enum type if downgrading
