"""Add grocery shopping and meal prep to schedule entries

Revision ID: 83adbc68b3fa
Revises: 20251212_2300
Create Date: 2025-12-13 08:24:13.324171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83adbc68b3fa'
down_revision: Union[str, None] = '20251212_2300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_entries', sa.Column('grocery_list', sa.JSON(), nullable=True))
    op.add_column('schedule_entries', sa.Column('prep_instructions', sa.JSON(), nullable=True))
    
    # Drop old constraint and add new one that handles grocery_shopping and meal_prep types
    op.drop_constraint('valid_entry_reference', 'schedule_entries', type_='check')
    op.create_check_constraint(
        'valid_entry_reference',
        'schedule_entries',
        "(entry_type = 'workout' AND workout_id IS NOT NULL AND meal_id IS NULL AND grocery_list IS NULL AND prep_instructions IS NULL) OR "
        "(entry_type = 'meal' AND meal_id IS NOT NULL AND workout_id IS NULL AND grocery_list IS NULL AND prep_instructions IS NULL) OR "
        "(entry_type = 'grocery_shopping' AND workout_id IS NULL AND meal_id IS NULL AND grocery_list IS NOT NULL AND prep_instructions IS NULL) OR "
        "(entry_type = 'meal_prep' AND workout_id IS NULL AND meal_id IS NULL AND grocery_list IS NULL AND prep_instructions IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old constraint
    op.drop_constraint('valid_entry_reference', 'schedule_entries', type_='check')
    op.create_check_constraint(
        'valid_entry_reference',
        'schedule_entries',
        "(entry_type = 'workout' AND workout_id IS NOT NULL AND meal_id IS NULL) OR "
        "(entry_type = 'meal' AND meal_id IS NOT NULL AND workout_id IS NULL)"
    )
    
    op.drop_column('schedule_entries', 'prep_instructions')
    op.drop_column('schedule_entries', 'grocery_list')
    # ### end Alembic commands ###
