"""Add Schedule and ProgressRecord models for User Story 2

Revision ID: 8c87f613d348
Revises: 2318a771a6ac
Create Date: 2025-11-17 12:42:14.719066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c87f613d348'
down_revision: Union[str, None] = '2318a771a6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fitness_plan_id', sa.UUID(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('workouts_completed_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('meals_completed_today', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('weight_lbs', sa.Numeric(), nullable=True),
    sa.Column('body_fat_percentage', sa.Numeric(), nullable=True),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weekly_adherence_rate', sa.Numeric(), nullable=True),
    sa.Column('total_workouts_completed', sa.Integer(), nullable=True),
    sa.Column('current_streak_days', sa.Integer(), nullable=True),
    sa.Column('milestone_achieved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('milestone_description', sa.Text(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('energy_level IS NULL OR (energy_level BETWEEN 1 AND 10)', name='valid_energy_level'),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_records_date', 'progress_records', ['record_date'], unique=False)
    op.create_index('idx_progress_records_milestones', 'progress_records', ['milestone_achieved'], unique=False, postgresql_where='milestone_achieved = true')
    op.create_index('idx_progress_records_type', 'progress_records', ['record_type'], unique=False)
    op.create_index('idx_progress_records_user', 'progress_records', ['user_id'], unique=False)
    op.create_index('idx_progress_records_user_date', 'progress_records', ['user_id', 'record_date'], unique=False, postgresql_using='btree')
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fitness_plan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('recalculation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fitness_plan_id'], ['fitness_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fitness_plan_id', name='one_schedule_per_plan')
    )
    op.create_index('idx_schedules_fitness_plan', 'schedules', ['fitness_plan_id'], unique=False)
    op.create_index('idx_schedules_user', 'schedules', ['user_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.Time(), nullable=True),
    sa.Column('workout_id', sa.UUID(), nullable=True),
    sa.Column('meal_id', sa.UUID(), nullable=True),
    sa.Column('completion_status', sa.String(length=50), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(entry_type = 'workout' AND workout_id IS NOT NULL AND meal_id IS NULL) OR (entry_type = 'meal' AND meal_id IS NOT NULL AND workout_id IS NULL)", name='valid_entry_reference'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_entries_date', 'schedule_entries', ['entry_date'], unique=False)
    op.create_index('idx_schedule_entries_meal', 'schedule_entries', ['meal_id'], unique=False)
    op.create_index('idx_schedule_entries_schedule', 'schedule_entries', ['schedule_id'], unique=False)
    op.create_index('idx_schedule_entries_status', 'schedule_entries', ['completion_status'], unique=False)
    op.create_index('idx_schedule_entries_user_date', 'schedule_entries', ['schedule_id', 'entry_date'], unique=False)
    op.create_index('idx_schedule_entries_workout', 'schedule_entries', ['workout_id'], unique=False)
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.create_unique_constraint(None, 'exercises', ['id'])
    op.create_unique_constraint(None, 'fitness_plans', ['id'])
    op.create_unique_constraint(None, 'meal_plans', ['id'])
    op.create_unique_constraint(None, 'meals', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'phases', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'workout_plans', ['id'])
    op.create_unique_constraint(None, 'workouts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='unique')
    op.drop_constraint(None, 'workout_plans', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'phases', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'meals', type_='unique')
    op.drop_constraint(None, 'meal_plans', type_='unique')
    op.drop_constraint(None, 'fitness_plans', type_='unique')
    op.drop_constraint(None, 'exercises', type_='unique')
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_index('idx_schedule_entries_workout', table_name='schedule_entries')
    op.drop_index('idx_schedule_entries_user_date', table_name='schedule_entries')
    op.drop_index('idx_schedule_entries_status', table_name='schedule_entries')
    op.drop_index('idx_schedule_entries_schedule', table_name='schedule_entries')
    op.drop_index('idx_schedule_entries_meal', table_name='schedule_entries')
    op.drop_index('idx_schedule_entries_date', table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index('idx_schedules_user', table_name='schedules')
    op.drop_index('idx_schedules_fitness_plan', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('idx_progress_records_user_date', table_name='progress_records', postgresql_using='btree')
    op.drop_index('idx_progress_records_user', table_name='progress_records')
    op.drop_index('idx_progress_records_type', table_name='progress_records')
    op.drop_index('idx_progress_records_milestones', table_name='progress_records', postgresql_where='milestone_achieved = true')
    op.drop_index('idx_progress_records_date', table_name='progress_records')
    op.drop_table('progress_records')
    # ### end Alembic commands ###
